voxel_grid_size: [5, 5]
map_resolution: 5
max_map_resolution: 20
gen_resolution_inc: 5
generations: 10
population_size: 50
top_n_survive: 5
simulation_time: 5
early_stopping_threshold: 1e-3
diversity_threshold: 0.05
no_improvement_limit: 5
save_dir: "saved_data"
env_name: "Walker-v0"
exp_name: "sim_cooptimization"